version: "3.8"
services:
  mongodb:
    image: 'mongo'
    volumes:
      - complete:/data/db
    # environment:
      # MONGO_INITDB_ROOT_USERNAME: max
      # MONGO_INITDB_ROOT_USERNAME: secret
      # - MONGO_INITDB_ROOT_USERNAME = max
      # - MONGO_INITDB_ROOT_PASSWORD = secret
    # env_file:
    #   - ./env/mongo.env
    # networks:
    #   - vernon
  backend:
    build: ./backend
    # build: 
    #   context: ./backend
    #   dockerfile: Dockerfile
    ports:
      - '80:80'
    volumes:
      - logs:/app/logs
      - ./backend:/app
      - /app/node_modules
    depends_on:
      - mongodb 


  frontend:
    build: ./frontend
    ports:
      - '3000:3000'
    volumes:
      - ./frontend/src:/app/src
    stdin_open : true
    tty: true 

    depends_on:
      - backend

volumes:
  complete:
  logs: